COMMON:
  NAME: "Awesome-Digital-Human"
  VERSION: "v0.0.1"
  LOG_LEVEL: "DEBUG"
SERVER:
  IP: "0.0.0.0"
  PORT: 8000
  ENGINES:
    ASR: 
      SUPPORT_LIST: ["localWisperAPI.yaml"]
      DEFAULT: "localWisperAPI.yaml"
    LLM: 
      SUPPORT_LIST: ["openaiAPI.yaml" ]
      DEFAULT:  "openaiAPI.yaml"
    TTS: 
      SUPPORT_LIST: [ "edgeAPI.yaml","coquiTT.yaml"]
      DEFAULT: "coquiTT.yaml"
  AGENTS: 
    SUPPORT_LIST: [ "repeaterAgent.yaml","localLLamaCppAgent.yaml"]
    DEFAULT: "localLLamaCppAgent.yaml" 