base_model: "meta-llama/Llama-2-7b-hf"
lora_r: 8
lora_alpha: 16
lora_dropout: 0.1
target_modules: ["q_proj", "v_proj"]
batch_size: 4
learning_rate: 5e-5
epochs: 3

# RAG 配置
rag_retriever:
  type: "simple"   # 可以选择 simple 或 advanced（针对更复杂的检索方式）
  knowledge_base_path: "./knowledge_base"  # 用户知识库的文件夹路径
  top_k: 3  # 每次检索返回的文档数
